config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'listings#index'
  
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  
  get '/my_listings' => 'listings#my_listings'
  get '/my_bids' => 'bids#my_bids'
  get '/bids_on_my_listings' => 'bids#bids_on_my_listings'
  get '/find' => 'listings#find'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/users/:user_id/message' => 'conversations#new'

  resources :users, only: :show do
    resources :reviews, only: [:new, :create, :show]
  end

  resources :conversations, except: [:edit, :update, :new] do
    resources :messages, only: [:new, :create]
  end

  resources :skills, only: [:index, :show]

  resources :listings do
    resources :bids
  end
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  validates :amount, :message, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    has_many :participants
    has_many :users, through: :participants

    accepts_nested_attributes_for :messages
    accepts_nested_attributes_for :participants

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bids
  validates :title, :description, presence: true

  scope :search, ->(string) {where("title LIKE ?", "%#{string}%") if string.present? }

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  validates :message, presence: true

  scope :descending, -> {order(created_at: :desc)}
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  validates :comment, :skill, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
end

app/models/user.rb
class User < ApplicationRecord
    has_many :listings
    has_many :bids
    has_many :bids_on_my_listings, :through => :listings, :source => :bids
    has_many :reviews
    has_many :skills, -> {distinct}, through: :reviews
    has_many :participants
    has_many :conversations, through: :participants

    has_secure_password 
    validates :username, presence: true
    validates :username, uniqueness: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

    helper_method :owns_bid?

    before_action :find_listing, except: [:my_bids, :bids_on_my_listings]
    before_action :find_bid, only: [:show, :edit, :update, :destroy]

    before_action :require_login
    before_action :require_owns_listing, only: [:index]
    before_action :require_owns_bid, only: [:edit, :update, :destroy]

    def index
        @bids = @listing.bids
    end

    def my_bids
        @bids = Bid.where(user_id: current_user.id)
        render :index
    end

    def bids_on_my_listings
        @bids = current_user.bids_on_my_listings
        render :index
    end

    def show 
        if owns_bid? || owns_listing?
            render :show
        else
            redirect_to '/listings/index'
        end
    end

    def new
        @bid = @listing.bids.build
    end

    def create 
        @bid = @listing.bids.build(bid_params)
        if @bid.save
            redirect_to listing_bid_path(@listing, @bid)
        else
            flash.now[:error] = @bid.errors.full_messages
            render :new
        end

    end

    def edit 
    end

    def update
        if @bid.update(bid_params)
            redirect_to listing_bid_path(@listing, @bid)
        else
            flash.now[:error] = @bid.errors.full_messages
            render :edit
        end
    end
    
    def destroy
        @bid.delete
        flash[:notice] = "Bid for '#{@listing.title}' was deleted."
        redirect_to listing_path(@listing)
    end

    private

    def find_listing
        @listing = Listing.find(params[:listing_id])
    end

    def find_bid
        @bid = Bid.find(params[:id])
    end

    def require_owns_bid
        redirect_to controller: 'listings', action: 'index' unless owns_bid?
    end

    def owns_bid?
        current_user == @bid.user
    end

    def bid_params
        params.require(:bid).permit(:amount, :message, :user_id)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    before_action :find_listing, only: [:show, :edit, :update, :destroy]
    before_action :require_login, except: [:index, :find, :show]
    before_action :require_owns_listing, only: [:edit, :update, :destroy]
    
    def index 
        @listings = Listing.all
    end

    def find
        @listings = Listing.search(params[:query])
    end
    
    def my_listings
        @listings = Listing.where(user_id: current_user.id)
        render :find
    end

    def show
    end

    def new
        @listing = Listing.new
    end

    def create 
        user = current_user
        @listing = user.listings.build(listing_params)
        if @listing.save
            redirect_to listing_path(@listing)
        else
            flash.now[:error] = @listing.errors.full_messages
            render :new
        end
    end

    def edit
    end

    def update
        if @listing.update(listing_params)
            redirect_to listing_path(@listing)
        else
            flash.now[:error] = @listing.errors.full_messages
            render :edit
        end
    end
    
    def destroy
        @listing.bids.destroy_all
        @listing.delete
        flash[:notice] = "'#{@listing.title}' was deleted."
        redirect_to listings_path
    end

    private

    def find_listing
        @listing = Listing.find(params[:id])
    end

    def listing_params
        params.require(:listing).permit(:title, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    before_action :find_user
    before_action :require_login
    
    def new
        @review = @user.reviews.build
    end

    def create 
        @review = @user.reviews.build(review_params)
        if @review.save
            redirect_to user_path(@user)
        else
            flash.now[:error] = @review.errors.full_messages
            render :new
        end
    end

    def show
        @review = Review.find(params[:id])
    end

    private

    def review_params
        params.require(:review).permit(:comment, :skill_id, :author)
    end

    def find_user
        @user = User.find(params[:user_id])
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    before_action :require_login
    
    def index   
        @skills = Skill.all
    end

    def show
        @skill = Skill.find(params[:id])
        @users = @skill.users
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :require_login, only: :show

    def new
        if !logged_in?
            render :new
        else
            redirect_to '/'
        end
    end

    def create
        @user = User.new(user_params)
            if @user.save
            return redirect_to controller: 'users', action: 'new' unless @user.save
            session[:user_id] = @user.id
            redirect_to '/'
        else
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/_form.html.erb
<%= form_for bid, url:url do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>    
    <label>Amount:</label><br>
    <%= f.number_field :amount %><br>
    <label>Message:</label><br>
    <%= f.text_area :message, cols: "50", rows: "4" %><br>
    <%= f.submit "Submit Bid", :class => "btn btn-success" %>
<% end %>

app/views/bids/edit.html.erb
<%= button_to "Back to Bid", listing_bid_path(@listing, @bid), method: "get", :class => "btn btn-outline-success"  %><br>
<h1>Edit Bid for '<%= @listing.title %>'</h1>
<%= render partial: 'form', locals: {bid: @bid, url:listing_bid_path(@listing, @bid)} %>

app/views/bids/index.html.erb
<%= button_to "Back to Listings", listings_path, method: "get", :class => "btn btn-outline-success"  %><br>
<ul style="list-style-type:none;">
    <% @bids.each do |b| %>
        <li><%= b.listing.title %> - <%= link_to b.amount, listing_bid_path(b.listing, b) %></li>
    <% end %>
</ul>

app/views/bids/new.html.erb
<%= button_to "Back to Listing", listing_path(@listing), method: "get", :class => "btn btn-outline-success"  %><br>
<h1>New Bid for '<%= @listing.title %>'</h1>
<%= render partial: 'form', locals: {bid: @bid, url:listing_bids_path(@listing)} %>

app/views/bids/show.html.erb
<%= button_to "Back to Listing", listing_path(@listing), method: "get", :class => "btn btn-outline-success"  %><br>
<h1>Bid for: <%= @listing.title %></h1>
<small>by: <%= link_to @bid.user.username, user_path(@bid.user) %></small>
<br><br>
<p>$<%= @bid.amount %></p>
<p><%= @bid.message %></p>
<% if owns_bid? %>
    <div class="btn-group">
        <%= button_to "Edit Bid", edit_listing_bid_path(@listing, @bid), method: "get", :class => "btn btn-outline-secondary" %>
        <%= button_to "Delete Bid", listing_bid_path(@listing, @bid), method: "delete", :class => "btn btn-outline-danger" %>
    </div>
<% end %>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
    <label>Title:</label><br>
    <%= f.text_field :title %><br>
    <label>Description:</label><br>
    <%= f.text_area :description, cols: "50", rows: "4"%><br><br>
    <%= f.submit "Submit Listing", :class => "btn btn-success" %>
<% end %>

app/views/listings/_listings.html.erb
<ul style="list-style-type:none;">
    <% @listings.each do |l| %>
        <li><%= l.updated_at.strftime("%-m/%-d/%Y") %> - <%= link_to l.title, listing_path(l) %></li>
    <% end %>
</ul>

app/views/listings/edit.html.erb
<%= button_to "Back to Listing", listing_path(@listing), method: "get", :class => "btn btn-outline-success"  %><br>
<h1>Edit Listing for '<%= @listing.title %>'</h1>
<%= render 'form' %>

app/views/listings/find.html.erb
<%= button_to "Back to all Listings", listings_path, method: "get", :class => "btn btn-outline-success" %>
<br>
<%= render 'listings' %>

app/views/listings/index.html.erb
<%= form_tag("/find", method: "get") do %>
  <label>Search Listings for: </label>
  <%= text_field_tag :query %>
  <input class="btn btn-success" type=submit value='Find Listing'>
<% end %>
<br>

<%= render 'listings' %>

app/views/listings/new.html.erb
<%= button_to "Back to Listings", listings_path, method: "get", :class => "btn btn-outline-success"  %><br>
<h1>New Listing</h1>
<%= render 'form' %>

app/views/listings/show.html.erb
<%= button_to "Back to Listings", listings_path, method: "get", :class => "btn btn-outline-success"  %><br>
<h1><%= @listing.title %></h1>
<small>Posted by: <%= @listing.user.username %></small>
<br><br>
<p><%= @listing.description %></p>
<% if logged_in? %>
    <% if owns_listing? %>
        <div class="btn-group">
            <%= button_to "View Bids", listing_bids_path(@listing), method: "get", :class => "btn btn-outline-success" %> 
            <%= button_to "Edit Listing", edit_listing_path(@listing), method: "get", :class => "btn btn-outline-secondary" %>
            <%= button_to "Delete Listing", listing_path(@listing), method: "delete", :class => "btn btn-outline-danger" %>
        </div>
    <% else %>
        <%= button_to "Make Bid", new_listing_bid_path(@listing), method: "get", :class => "btn btn-outline-success" %>
    <% end %>
<% end %>

app/views/skills/index.html.erb
<%= button_to "Back to Listings", listings_path, method: "get", :class => "btn btn-outline-success" %>
<br>
<h2>Browse Contractors by Category:</h2>
<br>
<ul style="list-style-type:none;">
    <% @skills.each do |skill| %>
        <li><%= link_to skill.name, skill_path(skill) %></li>
    <% end %>
</ul>

app/views/skills/show.html.erb
<%= button_to "Back to Contractors", skills_path, method: "get", :class => "btn btn-outline-success" %>
<br>
<h3>All <%= @skill.name %>s:</h3>
<br>
<ul style="list-style-type:none;">
    <% @users.each do |user| %>
        <li><%= link_to user.username, user_path(user) %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1><br>
<%= form_for :user, url: '/signup' do |f| %>
    <label>Username: </label><br>
    <%= f.text_field :username %><br>
    <label>Password: </label><br>
    <%= f.password_field :password %><br>
    <label>Password Confirmation: </label><br>
    <%= f.password_field :password_confirmation %><br><br>
    <%= f.submit "Sign Up", :class => 'btn btn-success' %>
<% end %> 

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<br>
<div class="btn-group">
    <%= button_to "Message #{@user.username}", "/users/#{@user.id}/message", method: "get", :class => "btn btn-outline-success" %>
    <%= button_to "Leave a Review", new_user_review_path(@user), method: "get", :class => "btn btn-success" %>
</div>
<br><br>
<h5><%= @user.username %>'s Skills:</h5>
<ul>
    <% @user.skills.each do |s| %>
        <li><%= s.name %></li>
    <% end %>
</ul>
<hr>
<% @user.reviews.each do |r| %>
    <small>Review from <%= r.author %>:</small>
    <p><%= r.comment %></p>
    <hr>
<% end %>