config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'listings#index'
  
  match '/auth/:provider/callback', to: 'sessions#github', via: [:get, :post]
  
  get '/my_listings' => 'listings#my_listings'
  get '/my_bids' => 'bids#my_bids'
  get '/bids_on_my_listings' => 'bids#bids_on_my_listings'
  get '/find' => 'listings#find'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/users/:user_id/message' => 'conversations#new'

  resources :users, only: :show do
    resources :reviews, only: [:new, :create, :show]
  end

  resources :conversations, except: [:edit, :update, :new] do
    resources :messages, only: [:new, :create]
  end

  resources :skills, only: [:index, :show]

  resources :listings do
    resources :bids
  end
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  validates :amount, :message, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    has_many :participants
    has_many :users, through: :participants

    accepts_nested_attributes_for :messages
    accepts_nested_attributes_for :participants

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bids
  validates :title, :description, presence: true

  scope :search, ->(string) {where("title LIKE ?", "%#{string}%") if string.present? }

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  validates :message, presence: true

  scope :descending, -> {order(created_at: :desc)}
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  validates :comment, :skill, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
end

app/models/user.rb
class User < ApplicationRecord
    has_many :listings
    has_many :bids
    has_many :bids_on_my_listings, :through => :listings, :source => :bids
    has_many :reviews
    has_many :skills, -> {distinct}, through: :reviews
    has_many :participants
    has_many :conversations, through: :participants

    has_secure_password 
    validates :username, presence: true
    validates :username, uniqueness: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

    helper_method :owns_bid?

    before_action :find_listing, except: [:my_bids, :bids_on_my_listings]
    before_action :find_bid, only: [:show, :edit, :update, :destroy]

    before_action :require_login
    before_action :require_owns_listing, only: [:index]
    before_action :require_owns_bid, only: [:edit, :update, :destroy]

    def index
        @bids = @listing.bids
    end

    def my_bids
        @bids = Bid.where(user_id: current_user.id)
        render :index
    end

    def bids_on_my_listings
        @bids = current_user.bids_on_my_listings
        render :index
    end

    def show 
        if owns_bid? || owns_listing?
            render :show
        else
            redirect_to '/listings/index'
        end
    end

    def new
        @bid = @listing.bids.build
    end

    def create 
        @bid = @listing.bids.build(bid_params)
        if @bid.save
            redirect_to listing_bid_path(@listing, @bid)
        else
            flash.now[:error] = @bid.errors.full_messages
            render :new
        end

    end

    def edit 
    end

    def update
        if @bid.update(bid_params)
            redirect_to listing_bid_path(@listing, @bid)
        else
            flash.now[:error] = @bid.errors.full_messages
            render :edit
        end
    end
    
    def destroy
        @bid.delete
        flash[:notice] = "Bid for '#{@listing.title}' was deleted."
        redirect_to listing_path(@listing)
    end

    private

    def find_listing
        @listing = Listing.find(params[:listing_id])
    end

    def find_bid
        @bid = Bid.find(params[:id])
    end

    def require_owns_bid
        redirect_to controller: 'listings', action: 'index' unless owns_bid?
    end

    def owns_bid?
        current_user == @bid.user
    end

    def bid_params
        params.require(:bid).permit(:amount, :message, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :require_login, only: :show

    def new
        if !logged_in?
            render :new
        else
            redirect_to '/'
        end
    end

    def create
        @user = User.new(user_params)
            if @user.save
            return redirect_to controller: 'users', action: 'new' unless @user.save
            session[:user_id] = @user.id
            redirect_to '/'
        else
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
    <% flash[:error].each do |error| %>
        <div class="alert alert-danger">
        <%= error %>
        </div>
    <% end %>
<% end %>
<%= content_tag(:div, content_tag("p", flash[:notice]), class: "alert alert-success") if flash[:notice] %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container">
        <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <%= button_to "Home", root_path, method: :get, :class => 'btn btn-light' %>
                </li>
                <% if logged_in? %>
                    <li class="nav_item">
                        <%= button_to "New Listing", new_listing_path, method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "My Listings", '/my_listings', method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "My Bids", '/my_bids', method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "Bids On My Listings", '/bids_on_my_listings', method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "View Contractors", skills_path, method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "Messages", conversations_path, method: :get, :class => 'btn btn-success'%>
                    </li>
                    <li class="nav_item">
                        <%= button_to "Logout", logout_path, :class => 'btn btn-dark'%>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= button_to "Login", login_path, method: :get, :class => 'btn btn-success' %>
                    </li>
                    <li class="nav-item">
                        <%= button_to "Sign Up", signup_path, method: :get, :class => 'btn btn-success' %>
                    </li>
                    <li class="nav-item">
                        <%= button_to 'Sign in with GitHub', '/auth/github', method: :post, :class => 'btn btn-dark'%>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KjsList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <br><br>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>